# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pizzashopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0002_auto_20171119_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sushi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=pizzashopapp.models.get_sushi_upload_path)),
                ('price', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzashopapp.PizzaShop')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to=pizzashopapp.models.get_pizza_upload_path),
        ),
    ]
